### ISSUE TITLE
Cops name

### ISSUE THREAD

**Issue by yas-ayob** [IcyFlameX/GTACops#1]
HEY There
in the 1.4.1 version there is a bug with the cops name 
we cannot change the name and the name is zombie pigman[default]
please fix asap!
Also can you make it so that cops go away and so does your wanted level after a certain amount of time!
thanks

**Comment by IcyFlameX** [comment]
Hi thanks for reporting :). Will fix it in next Version.

**Comment by yas-ayob** [comment]
1.4.1 is the version and server version 1.8.8

**Comment by IcyFlameX** [comment]
Are there any errors in console?
Change the Color code in config 
"&4&lPolice" to "&9&lCops"
Then save it and do a /gtrareload. 
If that doesn't work, close the server. Edit it and restart it. Tell me if it works.

**Comment by yas-ayob** [comment]
Will check for errors when I'm back from school and I'll change the color code

**Comment by IcyFlameX** [comment]
If the issue is fixed, please close it and give a rating :)

**Comment by yas-ayob** [comment]
Hey..i have not being able to log on to my server because of school I will get on today and tell u...ill give this a rating even if it's not fixed because u are a very nice and active dev.
