### ISSUE TITLE
Plugin doesent work..

### ISSUE THREAD

**Issue by StromeX123** [IcyFlameX/GTACops#3]
Hi, this plugin doesent work..... No count murders..
No give starts..
I tested this plugin in 4 servers... 1.8, 1.11.2, 1.12, 1.9 and no work..

**Comment by IcyFlameX** [comment]
Is there any error popping up in console?
Make sure you have MvDWplaceholderAPI and vault.

**Comment by StromeX123** [comment]
Console no send error...
Yes i have MVD and Vault.

**Comment by StromeX123** [comment]
[http://www.kepfeltoltes.eu/view.php?filename=705N_vtelen.png](url)

**Comment by IcyFlameX** [comment]
Check if the plugin is loaded ingame with the help of plugman or essentials. I will try to help you on 20th. I am currently a bit busy. Sorry for the inconvenience. Can assure you, I will be in contact.

**Comment by IcyFlameX** [comment]
Check if the plugin is loaded ingame with the help of plugman or essentials. I will try to help you on 20th. I am currently a bit busy. Sorry for the inconvenience. Can assure you, I will be in contact.

**Comment by StromeX123** [comment]
Yes the plugin is loaded.
And work /murders but i kill 3 player and murders is 0.

**Comment by IcyFlameX** [comment]
Ok is there any data.yml file created in the folder? Also due to my exams I can't test my plugin right now. I will be able to help on 20th due to a short break that time. Can you please wait? I will do my best to help you.

**Comment by IcyFlameX** [comment]
Hello i downloaded the plugin and checked it in my localhost. It is working perfectly fine. Is it still not working for you ?

**Comment by IcyFlameX** [comment]
Since there has been no response I am obliged to close the case.
