### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zBoringDrop** [IcyFlameX/GTACops#4]
Hey, why your plugin doesnt work in my server?
I have also vault!
Spigot 1.12
Logs: https://pastebin.com/ED0U9f7a

**Comment by IcyFlameX** [comment]
Hello,
Thanks for posting your issue.
Can you provide me with the link to the site of vault plugin? I want to know if you are using the spigot one or the bukkit one.

**Comment by zBoringDrop** [comment]
Bukkit

**Comment by IcyFlameX** [comment]
Ok I will try to see where's the problem and keep you updated with it.

**Comment by IcyFlameX** [comment]
Download Vault from here: https://ci.md-5.net/job/Vault/
Use Version 1.6.7
As for the actual issue, Vault isn't an economy plugin, it's an API that provides an interface to other plugins. So you need to either have your own custom coded economy plugin which supports vault or you can use the economy plugins as mentioned from their website.
![image](https://user-images.githubusercontent.com/19507043/40573046-656dc788-60d8-11e8-9fe9-4e46c8715176.png)

**Comment by zBoringDrop** [comment]
I must update Vault in all my servers?

**Comment by IcyFlameX** [comment]
Not necessary but it is advisable to use the one I sent because it is updated by @MD to make it run perfectly fine with 1.12.2. Yours should work fine. Just make sure you have an economy plugin.

**Comment by zBoringDrop** [comment]
So you suggest me of update Vault also in servers with different version ad 1.9 or 1.8.8?

**Comment by IcyFlameX** [comment]
No, it's perfectly fine. You can use your current version of vault.
Did the plugin work now ?

**Comment by zBoringDrop** [comment]
I cant test now, later i will test with new Vault :)

**Comment by IcyFlameX** [comment]
Ok, It's not compulsory for you to use any other economy plugin. If you are using Essentials, then that will work also. So if you want to avoid any other economy plugin use Essentials.

**Comment by zBoringDrop** [comment]
i'm using "Coins" plugin for economy.
Oh it seems to work ^^
If i see error i will report them here!

Another thing, why you don't do all this system with npcs?

**Comment by IcyFlameX** [comment]
The main reason being is, if you don't have a good hardware to run the server, NPC can be a real problem, since it causes too much lag and decreases tps. That's why I decided to use the Minecraft default entitiy zombie pigman which won't cause any lag and make it a smooth experience. Anyways hope you enjoy the plugin. Please Do Rate the plugin on my page.
Also if you want to report another issue, make another report in GitHub. I'm closing this one. Thank You for your patience and sorry for the inconvenience. Please Do Rate!
